version: '3.4'
services:
  mongo-quizz:
    image: mongo:latest
    container_name: mongo-quizz
    ports:
     - "27017:27017"
    volumes:
     - /home/local/mongodb:/data/db
  quizz:
    image: node:10
    container_name: quizz
    working_dir: /app
    command: 
       sh -c "npm install && npm start"
    ports:
     - "3000:3000"
    environment:
      IP_DB: mongo-quizz
    volumes:
     - .:/app
#    networks:
#      - poc-rcs
#networks:
#  poc-rcs:
#    external: true